spring:
  application:
    name: dhuSoftware
  datasource:
    url: jdbc:mysql://localhost:3306/dhusoftware?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000
      max-request-size: 10000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 13145