export type JobInfoMetadata = {
    "pdf-pages": number;
    "pdf-real-pages": number;
    "pdf-rawTextLength": number;
    "pdf-mdLength": number;
    "pdf-time": number;
    "pdf-ocrTime": number;
    "pdf-image-convertTime": number;
    "pdf-pdfToHTMLTime": number;
    "pdf-llmTime": number;
    "pdf-inputTokens": number;
    "pdf-outputTokens": number;
    "pdf-image-ocr-count": number;
    "pdf-image-ocr-failed-count": number;
    "pdf-image-ocr-success-count": number;
    "pdf-image-ocr-empty-count": number;
    "pdf-image-ocr-hadText-count": number;
    "pdf-image-ocr-pixels": number;
};

export type JobInfoOptions = {
    job_record_id: string;
    jobCreatedAtTimestamp: number;
    jobOutOfQueueTimestamp: number;
    jobTimeoutInSeconds: number;
    jobTimeoutExtraTimePerPageInSeconds: number;
    fileName: string;
    logFiles: boolean;
    fastMode: boolean;
    language: string;
    template: string | null;
    skipDiagonalText: boolean;
    invalidateCache: boolean;
    model: string;
    vendorAPIKey: string | null;
    multimodalPipeline: boolean;
    premiumMode: boolean;
    continuousMode: boolean;
    doNotUnrollColumns: boolean;
    doNotCache: boolean;
    pageSeparator: string | null;
    fileId: string | null;
    webhookUrl: string | null;
    boundingBox: string | null;
    bboxLeft: number | null;
    bboxRight: number | null;
    bboxTop: number | null;
    bboxBottom: number | null;
    targetPages: string | null;
    pagePrefix: string | null;
    pageSuffix: string | null;
    takeScreenshot: boolean;
    isFormattingInstruction: boolean;
    inputS3Path: string;
    inputS3Region: string;
    outputS3PathPrefix: string;
    outputS3Region: string;
    azureOpenAiKey: string | null;
    azureOpenAiApiVersion: string | null;
    azureOpenAiDeploymentName: string | null;
    azureOpenAiEndpoint: string | null;
    annotateLinks: boolean | null;
    guessXLSXSheetName: boolean;
    inputURL: string | null;
    httpProxy: string | null;
    disableImageExtraction: boolean;
    disableOcr: boolean;
    autoMode: boolean;
    autoModeTriggerOnRegexpInPage: string | null;
    autoModeTriggerOnTextInPage: string | null;
    autoModeTriggerOnImageInPage: boolean;
    autoModeTriggerOnTableInPage: boolean;
    structuredOutput: boolean;
    structuredOutputJSONSchema: string | null;
    structuredOutputJSONSchemaName: string | null;
    outputPDFOfDocument: boolean;
    htmlMakeAllElementsVisible: boolean;
    htmlRemoveFixedElements: boolean;
    htmlRemoveNavigationElements: boolean;
    maxPages: number | null;
    extractCharts: boolean;
    extractLayout: boolean;
    formattingInstruction: string | null;
    complementalFormattingInstruction: string | null;
    contentGuidelineInstruction: string | null;
    spreadSheetExtractSubTables: boolean;
    strictModeImageExtraction: boolean;
    strictModeImageOCR: boolean;
    strictModeReconstruction: boolean;
    strictModeBuggyFont: boolean;
    ignoreDocumentElementsForLayoutDetection: boolean;
    outputTablesAsHTML: boolean;
    llmMD: boolean;
};

export type JobInfo = {
    status: "success" | "failure" | "pending";
    info: string;
    metadata: JobInfoMetadata;
    images: string[];
    charts: string[];
    options: JobInfoOptions;
};

export type JobResponse = {
    job_name: string;
    partitions: { file_parsing_id_partition: string };
    parameters: {
        custom_metadata: string | null;
        resource_info: string | null;
        userId: string;
        fileName: string;
        originalFileName: string;
        fileKey: string;
        inputUrl: string | null;
        httpProxy: string | null;
        fastMode: boolean;
        lang: string;
        template: string;
        pipelineId: string | null;
        outputBucket: string | null;
        fileId: string | null;
        fullFilePath: string | null;
        fromLLamaCloud: boolean;
        skipDiagonalText: boolean;
        invalidateCache: boolean;
        outputPDFOfDocument: boolean;
        gpt4o: boolean;
        openAIAPIKey: string;
        doNotUnrollColumns: boolean;
        spreadSheetExtractSubTables: boolean;
        extractLayout: boolean;
        htmlMakeAllElementsVisible: boolean;
        htmlRemoveFixedElements: boolean;
        htmlRemoveNavigationElements: boolean;
        guessXLSXSheetName: boolean;
        doNotCache: boolean;
        pageSeparator: string | null;
        boundingBox: string;
        bboxTop: number | null;
        bboxRight: number | null;
        bboxBottom: number | null;
        bboxLeft: number | null;
        targetPages: string;
        multimodalPipeline: boolean;
        multimodalModel: string;
        vendorAPIKey: string;
        pagePrefix: string;
        pageSuffix: string;
        webhookUrl: string;
        takeScreenshot: boolean;
        isFormattingInstruction: boolean;
        premiumMode: boolean;
        continuousMode: boolean;
        disableOcr: boolean;
        disableImageExtraction: boolean;
        annotateLinks: boolean;
        inputS3Path: string;
        inputS3Region: string;
        outputS3PathPrefix: string;
        outputS3Region: string;
        projectId: string;
        azureOpenAiDeploymentName: string | null;
        azureOpenAiEndpoint: string | null;
        azureOpenAiApiVersion: string | null;
        azureOpenAiKey: string | null;
        autoMode: boolean;
        autoModeTriggerOnTableInPage: boolean;
        autoModeTriggerOnImageInPage: boolean;
        autoModeTriggerOnRegexpInPage: string | null;
        autoModeTriggerOnTextInPage: string | null;
        structuredOutput: boolean;
        structuredOutputJSONSchema: string | null;
        structuredOutputJSONSchemaName: string | null;
        maxPages: number | null;
        extractCharts: boolean;
        formattingInstruction: string | null;
        complementalFormattingInstruction: string | null;
        contentGuidelineInstruction: string | null;
        jobTimeoutInSeconds: number | null;
        jobTimeoutExtraTimePerPageInSeconds: number | null;
        strictModeImageExtraction: boolean;
        strictModeImageOCR: boolean;
        strictModeReconstruction: boolean;
        strictModeBuggyFont: boolean;
        ignoreDocumentElementsForLayoutDetection: boolean;
        outputTablesAsHTML: boolean;
    };
    session_id: string | null;
    correlation_id: string | null;
    parent_job_execution_id: string | null;
    user_id: string;
    created_at: string;
    project_id: string;
    id: string;
    status: "success" | "failure" | "pending";
    error_code: string | null;
    error_message: string | null;
    attempts: number;
    started_at: string;
    ended_at: string;
    updated_at: string;
    data: any | null;
    jobInfo: JobInfo;
};