name: Publish Docker Images

on:
  release:
    types: [published]   # 只有发布 Release（点击“Publish release”）才触发

env:
  # 固定不敏感的仓库级变量，方便后面引用
  DOCKERHUB_REPO_BE: ridiculousbuffalo/featurequiz-BE
  DOCKERHUB_REPO_FE: ridiculousbuffalo/featureQuiz-FE
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # -------- Backend --------
          - name: backend
            context: .
            dockerfile: ./Dockerfile
            repo: ridiculousbuffalo/featurequiz-BE
          # -------- Frontend --------
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile
            repo: ridiculousbuffalo/featureQuiz-FE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (optional for multi‑arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract release tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build & push ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.repo }}:${{ env.TAG }}
            ${{ matrix.repo }}:latest   # 如果不想推 latest 就删掉这一行